import { StoreManager } from '../store/storeManager.js';
import { WorldEditor } from './editors/worldEditor.js';
import '../math/primitives/point.js';
import '../math/primitives/segment.js';
import '../math/primitives/polygon.js';
import '../math/primitives/envelope.js';
import '../math/utils.js';
import '../math/graph/graph.js';
import '../math/osm-importer/osm.js';
import '../rendering/pointRenderer.js';
import '../rendering/segmentRenderer.js';
import '../rendering/polygonRenderer.js';
import '../rendering/envelopeRenderer.js';
import '../world/types.js';
import '../world/corridor.js';
import '../world/generation/worldGenerator.js';
import '../world/items/tree.js';
import '../world/items/building.js';
import '../world/markings/marking.js';
import '../world/markings/stop.js';
import '../world/markings/start.js';
import '../world/markings/crossing.js';
import '../world/markings/parking.js';
import '../world/markings/light.js';
import '../world/markings/target.js';
import '../world/markings/yield.js';
import '../world/editors/markingEditor.js';
import '../world/editors/graphEditor.js';
import '../world/editors/stopEditor.js';
import '../world/editors/startEditor.js';
import '../world/editors/crossingEditor.js';
import '../world/editors/parkingEditor.js';
import '../world/editors/lightEditor.js';
import '../world/editors/targetEditor.js';
import '../world/editors/yieldEditor.js';
import '../world/editors/corridorEditor.js';
import '../world/trafficManager.js';
import '../world/world.js';
import '../world/loader/worldLoader.js';
import './editors/worldEditor.js';
import '../viewport/scaleIndicator.js';
import '../viewport/viewport.js';
import '../mini-map/miniMap.js';
import '../utils.js';
import '../car/loader/carLoader.js';
import '../store/types.js';
import '../store/storeManager.js';
import '../panels/templates/worldToolbarTemplate.js';
import '../panels/templates/shortcutsToolbarTemplate.js';
import '../panels/templates/worldLayersToolbarTemplate.js';
import '../panels/modeControls.js';
import '../panels/assetSelectors.js';
import '../panels/worldToolbar.js';
import '../panels/shortcutsToolbar.js';
import '../panels/worldLayersToolbar.js';
import '../panels/editorToolbar.js';
(async () => {
    await StoreManager.init();
    function resizeCanvas() {
        myCanvas.width = window.innerWidth;
        myCanvas.height = window.innerHeight;
    }
    resizeCanvas();
    miniMapCanvas.width = 150;
    miniMapCanvas.height = 150;
    const worldEditor = new WorldEditor(myCanvas, miniMapCanvas);
    window.addEventListener('resize', () => {
        resizeCanvas();
        worldEditor.animate();
    });
    worldEditor.animate();
})();
