import { StoreManager } from '../../store/storeManager.js';
import { SimulatorPageHost } from '../views/simulatorPageHost.js';
import { HumanBackpropSimulator } from './humanBackpropSimulator.js';
import '../../math/primitives/point.js';
import '../../math/primitives/segment.js';
import '../../math/primitives/polygon.js';
import '../../math/primitives/envelope.js';
import '../../math/utils.js';
import '../../math/graph/graph.js';
import '../../math/spatialGrid.js';
import '../../rendering/pointRenderer.js';
import '../../rendering/segmentRenderer.js';
import '../../rendering/polygonRenderer.js';
import '../../rendering/envelopeRenderer.js';
import '../../world/types.js';
import '../../world/corridor.js';
import '../../world/generation/worldGenerator.js';
import '../../world/items/tree.js';
import '../../world/items/building.js';
import '../../world/markings/marking.js';
import '../../world/markings/stop.js';
import '../../world/markings/start.js';
import '../../world/markings/crossing.js';
import '../../world/markings/parking.js';
import '../../world/markings/light.js';
import '../../world/markings/target.js';
import '../../world/markings/yield.js';
import '../../world/editors/markingEditor.js';
import '../../world/editors/graphEditor.js';
import '../../world/editors/stopEditor.js';
import '../../world/editors/startEditor.js';
import '../../world/editors/crossingEditor.js';
import '../../world/editors/parkingEditor.js';
import '../../world/editors/lightEditor.js';
import '../../world/editors/targetEditor.js';
import '../../world/editors/yieldEditor.js';
import '../../world/trafficManager.js';
import '../../world/world.js';
import '../../world/simple/simpleWorld.js';
import '../../world/loader/worldLoader.js';
import '../../camera/types.js';
import '../../camera/extrusion.js';
import '../../camera/camera.js';
import '../../viewport/scaleIndicator.js';
import '../../viewport/viewport.js';
import '../../mini-map/miniMap.js';
import '../../audio/sound.js';
import '../../neural-network/visualizer.js';
import '../../neural-network/network.js';
import '../../car/config.js';
import '../../car/physics/sensorRaycaster.js';
import '../../car/sensors/sensor.js';
import '../../car/controls/controls.js';
import '../../car/physics/carPhysics.js';
import '../../car/rendering/carRenderer.js';
import '../../car/brain/carBrainAdapter.js';
import '../../car/car.js';
import '../../car/loader/carLoader.js';
import '../../store/types.js';
import '../../store/storeManager.js';
import '../../ui/molecules/worldToolbarTemplate.js';
import '../../ui/molecules/layoutToolbarTemplate.js';
import '../../ui/molecules/animationLoopToolbarTemplate.js';
import '../../ui/molecules/shortcutsToolbarTemplate.js';
import '../../ui/molecules/modeControls.js';
import '../../ui/molecules/assetSelectors.js';
import '../../ui/molecules/worldToolbar.js';
import '../../ui/molecules/layoutToolbar.js';
import '../../ui/molecules/animationLoopToolbar.js';
import '../../ui/molecules/shortcutsToolbar.js';
import '../../simulator/spatialGridUtils.js';
import '../../simulator/training/modes/trafficFactory.js';
import '../../simulator/training/modes/borderCollision.js';
import '../../simulator/training/rendering/carRenderer.js';
import '../../simulator/rendering/layoutManager.js';
import '../../simulator/training/modes/simpleModeBehavior.js';
import '../../simulator/training/modes/worldModeBehavior.js';
import '../../simulator/training/genetics/storageManager.js';
import '../../simulator/training/genetics/poolManager.js';
import '../../simulator/humanTraining/templates/humanTrainingConfigModalTemplate.js';
import '../../simulator/humanTraining/templates/humanTrainingPanelTemplate.js';
import '../../ui/organisms/humanTrainingConfigModal.js';
import '../../ui/organisms/humanTrainingPanel.js';
import '../../simulator/views/simulatorPageHost.js';
import '../../simulator/core/simulatorShell.js';
import './humanBackpropSimulator.js';
(async () => {
    await StoreManager.init();
    const host = new SimulatorPageHost();
    const sim = new HumanBackpropSimulator(gameCanvas, networkCanvas, miniMapCanvas, cameraCanvas, host);
    window.__sim = sim;
    if (new URLSearchParams(window.location.search).has('paused')) {
        sim.pause?.();
    }
})();
